apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pydemo-do-ext-secret-namespace
  namespace: example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: "pydemo-do-secret-store"
    kind: "SecretStore"
  target:
    name: "pydemo-secret-ss"
    creationPolicy: "Owner"
  data:
    - secretKey: "DEMO_SECRET"
      remoteRef:
        key: "secret/pydemo"
        property: "DEMO_SECRET"