apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: pydemo-do-secret-store
  namespace: example
spec:
  provider:
    vault:
      server: "https://:8200"
      path: "secret"
      version: "v1"
      caProvider:
        type: "Secret"
        name: "cabdlsec"
        key: "ca.crt"
        namespace: "default"
      auth:
        tokenSecretRef:
          name: "pydemo-do-vault-token"
          key: "token"