apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pydemo-do-ext-secret-cluster
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: "root-do-cluster-store"
    kind: "ClusterSecretStore"
  target:
    name: "pydemo-secret"
    creationPolicy: "Owner"
  data:
    - secretKey: "DEMO_SECRET"
      remoteRef:
        key: "secret/pydemo"
        property: "DEMO_SECRET"